import type { Order } from '../types/types'
import { mockProducts } from './mock-products'

export const mockOrders: Order[] = [
    {
        id: '101',
        name: 'Торт на день рождения Анны',
        clientName: 'Анна Кузнецова',
        clientPhone: '+7 (921) 555-12-33',
        orderPlatform: 'Instagram',
        deliveryType: 'delivery',
        address: 'ул. Ленина, 15',
        date: '2026-01-20',
        time: '15:00',
        products: [
            {
                id: 'o101-1',
                product: mockProducts[0],
                amount: 2,
                price: 2200,
                unit: 'kg',
            },
        ],
        paymentStatus: 'paid',
        status: 'delivered',
        paidAmount: 4400,
        totalPrice: 4400,
        inPlanner: false,
        extra: { delivery: 300, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-05T10:00:00.000Z',
        updatedAt: '2026-01-07T09:00:00.000Z',
    },
    {
        id: '102',
        name: 'Капкейки к корпоративу',
        clientName: 'ООО “Флорис”',
        clientPhone: '+7 (981) 330-11-22',
        orderPlatform: 'WhatsApp',
        deliveryType: 'pickup',
        products: [
            {
                id: 'o102-1',
                product: mockProducts[2],
                amount: 12,
                price: 350,
                unit: 'piece',
            },
        ],
        paymentStatus: 'partial',
        paidAmount: 2100,
        totalPrice: 4200,
        status: 'ready',
        inPlanner: true,
        extra: { delivery: 0, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-04T14:30:00.000Z',
        updatedAt: '2026-01-08T12:10:00.000Z',
    },
    {
        id: '103',
        name: 'Чизкейк на юбилей',
        clientName: 'Ирина Белова',
        clientPhone: '+7 (901) 210-00-77',
        orderPlatform: 'Avito',
        deliveryType: 'delivery',
        address: 'пр. Невский, 55',
        date: '2026-01-22',
        time: '17:00',
        products: [
            {
                id: 'o103-1',
                product: mockProducts[3],
                amount: 1,
                price: 2600,
                unit: 'kg',
            },
        ],
        paymentStatus: 'unpaid',
        paidAmount: 0,
        totalPrice: 2600,
        status: 'new',
        inPlanner: true,
        extra: { delivery: 400, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-06T12:00:00.000Z',
        updatedAt: '2026-01-06T12:00:00.000Z',
    },
    {
        id: '104',
        name: 'Торт “Наполеон” к юбилею мамы',
        clientName: 'Марина Волкова',
        clientPhone: '+7 (911) 777-22-11',
        orderPlatform: 'Flowwow',
        deliveryType: 'pickup',
        products: [
            {
                id: 'o104-1',
                product: mockProducts[1],
                amount: 1.5,
                price: 1800,
                unit: 'kg',
            },
        ],
        paymentStatus: 'paid',
        paidAmount: 2700,
        totalPrice: 2700,
        status: 'delivered',
        inPlanner: false,
        extra: { delivery: 0, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-02T09:00:00.000Z',
        updatedAt: '2026-01-03T14:00:00.000Z',
    },
    {
        id: '105',
        name: 'Мини-десерты к кофе-брейку',
        clientName: 'Кофейня “Бонжур”',
        orderPlatform: 'Telegram',
        deliveryType: 'delivery',
        address: 'ул. Кирова, 10',
        products: [
            {
                id: 'o105-1',
                product: mockProducts[5] ?? mockProducts[4],
                amount: 15,
                price: 120,
                unit: 'piece',
            },
            {
                id: 'o105-2',
                product: mockProducts[2],
                amount: 10,
                price: 350,
                unit: 'piece',
            },
        ],
        paymentStatus: 'partial',
        paidAmount: 2500,
        totalPrice: 4700,
        status: 'inWork',
        inPlanner: true,
        extra: { delivery: 500, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-08T11:00:00.000Z',
        updatedAt: '2026-01-09T09:20:00.000Z',
    },
    {
        id: '106',
        name: 'Торт “Шоколадный сюрприз”',
        clientName: 'Олег Громов',
        deliveryType: 'pickup',
        products: [
            {
                id: 'o106-1',
                product: mockProducts[0],
                amount: 1.5,
                price: 2200,
                unit: 'kg',
            },
        ],
        paymentStatus: 'paid',
        paidAmount: 3300,
        totalPrice: 3300,
        status: 'ready',
        inPlanner: false,
        extra: { delivery: 0, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-07T10:00:00.000Z',
        updatedAt: '2026-01-09T18:00:00.000Z',
    },
    {
        id: '107',
        name: 'Праздничный набор капкейков',
        clientName: 'Александра Петрова',
        clientPhone: '+7 (921) 111-44-88',
        deliveryType: 'delivery',
        address: 'ул. Молодёжная, 23',
        products: [
            {
                id: 'o107-1',
                product: mockProducts[2],
                amount: 6,
                price: 350,
                unit: 'piece',
            },
        ],
        paymentStatus: 'paid',
        paidAmount: 2100,
        totalPrice: 2100,
        status: 'delivered',
        inPlanner: false,
        extra: { delivery: 250, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-03T09:00:00.000Z',
        updatedAt: '2026-01-03T19:30:00.000Z',
    },
    {
        id: '108',
        name: 'Чизкейк для офиса',
        clientName: 'Артём Лисицын',
        orderPlatform: 'Telegram',
        deliveryType: 'pickup',
        products: [
            {
                id: 'o108-1',
                product: mockProducts[3],
                amount: 1,
                price: 2600,
                unit: 'kg',
            },
        ],
        paymentStatus: 'partial',
        paidAmount: 1300,
        totalPrice: 2600,
        status: 'inWork',
        inPlanner: true,
        extra: { delivery: 0, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-09T10:00:00.000Z',
        updatedAt: '2026-01-09T10:00:00.000Z',
    },
    {
        id: '109',
        name: 'Десерты к детскому празднику',
        clientName: 'Наталья Иванова',
        clientPhone: '+7 (999) 222-77-55',
        deliveryType: 'delivery',
        address: 'ул. Центральная, 45',
        products: [
            {
                id: 'o109-1',
                product: mockProducts[4],
                amount: 20,
                price: 120,
                unit: 'piece',
            },
            {
                id: 'o109-2',
                product: mockProducts[2],
                amount: 6,
                price: 350,
                unit: 'piece',
            },
        ],
        paymentStatus: 'paid',
        paidAmount: 4200,
        totalPrice: 4200,
        status: 'ready',
        inPlanner: true,
        extra: { delivery: 400, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-08T09:00:00.000Z',
        updatedAt: '2026-01-09T08:45:00.000Z',
    },
    {
        id: '110',
        name: 'Торт для свадьбы',
        clientName: 'Евгений и Мария',
        clientPhone: '+7 (950) 500-12-12',
        orderPlatform: 'Instagram',
        deliveryType: 'delivery',
        address: 'пр. Победы, 88',
        date: '2026-02-10',
        time: '12:00',
        products: [
            {
                id: 'o110-1',
                product: mockProducts[0],
                amount: 3,
                price: 2200,
                unit: 'kg',
            },
            {
                id: 'o110-2',
                product: mockProducts[1],
                amount: 1,
                price: 1800,
                unit: 'kg',
            },
        ],
        paymentStatus: 'partial',
        paidAmount: 4000,
        totalPrice: 8400,
        status: 'inWork',
        inPlanner: true,
        extra: { delivery: 600, urgency: 0, other: 0, discount: 0 },
        createdAt: '2026-01-05T15:00:00.000Z',
        updatedAt: '2026-01-09T10:00:00.000Z',
    },
]
